### ISSUE TITLE
Typing "https://pomochad.vercel.app/todos" straight into the URL bar results in an error

### ISSUE THREAD

**Issue by khaki32** [siduck/pomochad#3]
When I go to the /todos path straight from my bookmarks, I get a 404 error. I'm not sure if this is known, but in any case I presume that that's not supposed to happen. Great project by the way.

![Screenshot 2022-04-04 7 44 29 PM](https://user-images.githubusercontent.com/60853378/161601517-8381724c-868d-4b02-95ab-75de61504f2f.png)

**Comment by siduck** [comment]
Im not sure how to fix this issue, im still new to react

**Comment by khaki32** [comment]
Yeah I'm not very experienced with it either.

However, I think it's an issue with the Vercel deployment. According to the [Vercel docs](https://vercel.com/docs/concepts/edge-network/frequently-asked-questions#why-do-i-see-a-404-error-when-accessing-my-deployment), this happens because of the path not being found in the "Build Outputs" of the deployement. So you actually have content on this path through ``wouter``, but Vercel doesn't know about it and gives an error before ``wouter`` is even loaded. Just a theory. Maybe read about the [directory listing](https://vercel.com/docs/concepts/edge-network/directory-listing)?

**Comment by siduck** [comment]
its fixed now https://github.com/siduck/pomochad/commit/c07e3ad284b042b96fe08debdccd13032bf1ce71
